# !!!!!!!! Purpose is to store configs in one place. Not to use poetry. !!!!!!!!!!!!

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = ["RUF", "I"]

[tool.pyright]
include = ['app', 'test']

[tool.pytest.ini_options]
testpaths = ['test']

